name: Deploy to AlwaysData

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install SSH Client
              run: sudo apt-get install -y ssh

            - name: Add SSH key
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add SSH known hosts
              run: ssh-keyscan ssh-bbcr.alwaysdata.net >> ~/.ssh/known_hosts

            - name: Debug - Check permissions on target directory
              run: ssh bbcr_github@ssh-bbcr.alwaysdata.net "ls -ld /home/bbcr/www/"

            - name: Deploy to AlwaysData
              run: |
                  echo "Starting deployment..."
                  rsync -avz --ignore-times --delete --exclude='.github' ./ bbcr_github@ssh-bbcr.alwaysdata.net:/home/bbcr/www/
                  echo "Deployment completed successfully!"
              env:
                  USER: ${{ secrets.SSH_USERNAME }}
